config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  mount RailsAdmin::Engine => '/exit', as: 'rails_admin'
  
  devise_for :users
  # get 'dashboards/show'
  
  resources :coordinates
  resources :clients
  resources :quotes
  resources :tickets

  resources :invoices do
    collection do
      get 'cloudinary_invoices'
    end

    member do
      post 'save_to_cloudinary'
      get 'download_pdf'
      # delete 'destroy'
    end
  end
  
  get "invoices/:id/send", to: "invoices#send_mail", as: "send_mail"
  get 'print_quote/:id', to: 'quotes#show_another', as: 'print_quote'
end

app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :user
    belongs_to :client

    validates :quote_tva, presence: { message: "Le champ TVA doit être rempli" }
    validates :amount, presence: { message: "Le champ Montant doit être rempli" }
    validates :date, presence: { message: "Le champ Date doit être rempli" }
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_quote, only: %i[show edit update destroy show_another]
  
    def index
      @quotes = policy_scope(Quote)
    end
  
    def show
      authorize @quote
    end
  
    def show_another
    end
  
    def new
      @quote = Quote.new
      @clients = Client.where(user_id: current_user.id)
    end
  
    def edit
      @clients = Client.where(user_id: current_user.id)
    end
  
    def create
      @quote = Quote.new(quote_params)
      @quote.user = current_user
      if @quote.save!
        redirect_to quote_url(@quote), notice: "Devis créé"
      else
        flash.now[:alert] = "La création du devis a échoué."
        puts @quote.errors.full_messages # Afficher les messages d'erreur dans la console
        render :new, status: :unprocessable_entity
      end
    end
  
    def update
      authorize @quote
  
      if @quote.update(quote_params)
        redirect_to quote_url(@quote), notice: "Devis mis à jour"
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      authorize @quote
      @quote.destroy
  
      redirect_to quotes_url, notice: "Devis supprimé"
    end
  
    private
  
    def set_quote
      @quote = Quote.find(params[:id])
    end
  
    def quote_params
      params.require(:quote).permit(:amount, :my_company_siret, :date, :description, :quote_number, :prestation, :quote_tva, :client_id)
    end
  end
  

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<div class="container p-5" style="background-color: #fff; border: 1px solid #F4F4F4;">
  <%= simple_form_for(@quote) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <div class="d-flex justify-content-center">
          <%= f.input :quote_number, :label => "Numéro de devis" %>
      </div>
      <div class="facture-informations">
        <div class="my-infos">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, width: 80, height: 80, :gravity=>"faces", :crop=>"fill", class: "rounded mb-5" %>
          <% end %>
          <h4>devis éditée par :</h4>
          <%= current_user.first_name %> <%= current_user.last_name %><br>
          <%= current_user.address %><br>
          <%= current_user.phone %><br>
          <%= current_user.email %><br>
          <% if current_user.tva != nil %>
            N° TVA : <%= current_user.tva %><br>
          <% end %>
          Siret : <%= current_user.siret %>
        </div>
        <div class="informations-client">
          <div class="d-flex align-items-end flex-column">
              <%#= f.input :customer_name, :label => "Nom du client / Dénomination" %>
              <%#= f.input :customer_address, :label => "Adresse" %>
              <%#= f.input :customer_siret, :label => "N° siret" %>
               <%= f.input :client_id, collection: @clients, label_method: :first_name %>
          </div>
          <%#= raise %>
        </div>
      </div>
      <div class="d-flex justify-content-center w-100">
          <%= f.input :date, :label => "Date du devis", as: :string, input_html: { data: { controller: 'flatpickr' } } %>
      </div>
          <%= f.input :description, :label => "Titre du devis" %>
          <%= f.input :prestation, :label => "Prestations du devis :" %>
      <div class="d-flex align-items-end flex-column w-20">
          <%= f.input :quote_tva, value: "0%", collection: ["0%", "20%", "10%", "5.5%"], :label => "Taux de tva" %>
          <%= f.input :amount, :label => "Total HT" %>
      </div>
          <h4>Informations de paiements :</h4><br>
          IBAN : <%= current_user.infos_payment %><br><br>
           <h4>Conditions de paiements :</h4><br>
           <%= current_user.conditions %><br><br>
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-success", value: "Créer mon devis" %>
    </div>
  <% end %>
</div>

app/views/quotes/_quote.html.erb
<style>
.card-header{
  background-color: transparent;

}
#taille{
  height: 100px!important;
}
.card {
    border-radius: 10px;
    height: auto!important;
}
</style>


<div class="container p-5">
<div class="d-flex flex-wrap">
    <% @quotes.reverse_each do |quote| %>
      <div class="cardingspace">
        <% if quote.user_id == current_user.id %>
          <div class="card text-center m-1">
            <div class="card-header">
              Devis N°:  <%= quote.quote_number %>
            </div>
            <div class="card-body">
              <h4 class="card-title">Devis à : 
              <% if quote.client.denomination == nil %></h4>
                <%= quote.client.first_name %>
                <% else %>
                <%= quote.client.denomination %>
              <% end %>
              <p class="card-text"><%= quote.description %><br></p>
              <b> Total :</b>
                <% total_tva = (quote.amount * quote.quote_tva.to_f) / 100 %>
                <%= total_tva + quote.amount %>€ TTC</p>
              <div class="d-flex justify-content-between spacing-mob">
                <%= link_to "Aperçu", quote_path(quote), class: "btn btn-primary" %>
                <%= button_to "Supprimer", quote, method: :delete, class: "btn btn-danger" %>
                <% if quote.status == false %>
                  <%= link_to "Envoyer", send_mail_path(quote), class: "btn btn-success" %>
                <% end %>
              </div>
            </div>
            <% if quote.status == true %>
                <p class="mt-3" style="color: green;"><b>Devis envoyée</b></p>
            <% else %>
                <p class="mt-3" style="color: red;"><b>Devis non envoyée</b></p>
            <% end %>
            <div class="card-footer text-muted">
              Devis créée le : <%= quote.created_at %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/quotes/edit.html.erb
<style>
.footer.mt-5 {
    display: none;
}
</style>
<div class="container">
  <h1>Modifier mon devis</h1>
</div>
<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Voir ma facture", @invoice %> |
  <%= link_to "Retour à mes factures", invoices_path %>
</div>

app/views/quotes/index.html.erb
<style>
.footer.mt-5 {
    display: none;
}
</style>
<div class="container">  
  <h1>Vos Devis</h1>
  <div class="d-flex">
    <%= link_to "Créer", new_quote_path, class:"btn btn-success m-2 text-white" %>
    <%= link_to "Clients", clients_path, class:"btn btn-info m-2 text-white" %>
    <%= link_to "Factures", invoices_path, class:"btn btn-primary m-2 text-white" %>
  </div>
    <% if current_user.infos_payment == nil || current_user.conditions == nil %>
      <br><br>
      <p style="color: red;"> Vous n'avez pas configuré votre compte de facturation. <%= link_to "Cliquez ici", edit_user_registration_path %> pour le faire.</p>
    <% end %>
  <div id="quotes">
    <%= render "quote" %>
  </div>
</div>

app/views/quotes/new.html.erb
<style>
.footer.mt-5 {
    display: none;
}
</style>
<div class="container d-flex justify-content-between">
  <h1>Créer mon devis</h1>
  <%= link_to "Ajouter un client", new_client_path, class: "btn btn-primary m-3" %>
</div>

<%= render "form", quote: @quote %>

<br>

<div>
  <%= link_to "Retour à mes devis", quotes_path %>
</div>

app/views/quotes/show.html.erb
<style>
.footer.mt-5 {
    display: none;
}
/* button.btn.btn-danger {
    padding: 3px;
}
a.btn.btn-primary {
    padding: 3px;
}
a.btn.btn-success {
    padding: 3px;
} */
@media (max-width: 800px) {
button.btn.btn-danger {
    padding: 6px;
}
a.btn.btn-primary {
    padding: 6px;
}
a.btn.btn-success {
    padding: 6px;
}
}
</style>
<div class="container">
 <form class="d-flex justify-content-center">
    <%= link_to "Mes Devis", quotes_path, class: "btn btn-dark m-2 btn-mob" %>
    <%= link_to "Enregistrer", print_quote_path(@quote), target: "_blank", class: "btn btn-warning text-white m-2" %>
    <%#= link_to "Envoyer", send_mail_path(@quote), class: "btn btn-success m-2" %>
    <%= link_to "Modifier", edit_quote_path(@quote), class: "btn btn-primary m-2 p-2" %>
	<%= button_to "Supprimer", @quote, method: :delete, class: "btn btn-danger m-2" %>
  </form>
	<div class="invoice-box">
				<table cellpadding="0" cellspacing="0">
					<tr class="top">
						<td colspan="2">
							<table>
								<tr>
									<td class="title">
										<% if current_user.photo.attached? %>
						<%= cl_image_tag current_user.photo.key, :gravity=>"faces", :crop=>"fill", width: 80, height: 80, class: "rounded mb-5" %>
						<% end %>
									</td>

									<td>
										Devis n° #: <%= @quote.quote_number %><br />
										Créée: <%= @quote.date %><br />
									</td>
								</tr>
							</table>
						</td>
					</tr>

					<tr class="information">
						<td colspan="2">
							<table>
								<tr>
									<td>
										<%= current_user.first_name %> <%= current_user.last_name %><br />
										<%= current_user.address %><br />
					<%= current_user.phone %><br />
					<%= current_user.email %><br />
										N° Siret : <%= current_user.siret %><br />
					<%= current_user.tva if current_user.tva != nil %><br />
					<p class="mt-3 text-center"><b>Titre du devis : <%= @quote.description.camelcase %></b></p>
									</td>

									<td>
										<%= @quote.client.first_name %> <%= @quote.client.denomination %><br />
										<%= @quote.client.email %><br />
										<%= @quote.client.compagny_address %>
					<%= @quote.client.compagny_siret if @quote.client.compagny_siret != nil %>
									</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr class="heading">
						<td>Informations de paiements :</td>

						<td></td>
					</tr>

					<tr class="details">
						<td><%= current_user.infos_payment %></td>

						<td></td>
					</tr>

					<tr class="heading">
						<td>Description</td>

						<td>Prix HT</td>
					</tr>

					<tr class="item">
						<td><%= @quote.prestation %></td>

						<td><%= @quote.amount %>€ HT</td>
					</tr>

					<tr class="total">
			<% total_tva = ((@quote.amount * @quote.quote_tva.to_f) / 100) %>
						<td> Total TVA : <%= total_tva %>€</td>
						<td>Total: <%= total_tva + @quote.amount %>€ TTC</td>
					</tr>
			<td style="margin-top: 20px!important;"><%= current_user.conditions %></td>
				</table>
	</div>
</div>

app/views/quotes/show_another.html.erb
<style>
.footer.mt-5 {
    display: none;
}
.navbar.navbar-expand-sm.navbar-light.navbar-lewagon.fixed-top {
    display: none;
}
body {
    margin-top: 10px;
}
.container {
    min-width: 1000px;
}
</style>
<script type="text/javascript">
    object = document.querySelector("body");
    object.addEventListener("load", window.print());
</script>
<div class="container">
  <div class="invoice-box">
			<table cellpadding="0" cellspacing="0">
				<tr class="top">
					<td colspan="2">
						<table>
							<tr>
								<td class="title">
									  <% if current_user.photo.attached? %>
                      <%= cl_image_tag current_user.photo.key, :gravity=>"faces", :crop=>"fill", width: 80, height: 80, class: "rounded mb-5" %>
                    <% end %>
								</td>

								<td>
									Devis n° #: <%= @quote.quote_number %><br />
									Créée: <%= @quote.date %><br />
								</td>
							</tr>
						</table>
					</td>
				</tr>

				<tr class="information">
					<td colspan="2">
						<table>
							<tr>
								<td>
									<%= current_user.first_name %> <%= current_user.last_name %><br />
									<%= current_user.address %><br />
                  <%= current_user.phone %><br />
                  <%= current_user.email %><br />
									N° Siret : <%= current_user.siret %><br />
                  <%= current_user.tva if current_user.tva != nil %><br />
                  <p class="mt-3 text-center"><b>Titre du devis : <%= @quote.description.camelcase %></b></p>
								</td>

								<td>
									<%= @quote.client.first_name %> <%= @quote.client.denomination %><br />
									<%= @quote.client.email %><br />
									<%= @quote.client.compagny_address %>
                  <%= @quote.client.compagny_siret if @quote.client.compagny_siret != nil %>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr class="heading">
					<td>Informations de paiements :</td>

					<td></td>
				</tr>

				<tr class="details">
					<td><%= current_user.infos_payment %></td>

					<td></td>
				</tr>

				<tr class="heading">
					<td>Description</td>

					<td>Prix HT</td>
				</tr>

				<tr class="item">
					<td><%= @quote.prestation %></td>

					<td><%= @quote.amount %>€ HT</td>
				</tr>

				<tr class="total">
          <% total_tva = (@quote.amount * @quote.quote_tva.to_f) / 100 %>
					<td> Total TVA : <%= total_tva %>€</td>
					<td>Total: <%= total_tva + @quote.amount %>€ TTC</td>
				</tr>
          <td style="margin-top: 20px!important;"><%= current_user.conditions %></td>
			</table>
		</div>
</div>