config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  mount RailsAdmin::Engine => '/exit', as: 'rails_admin'
  
  devise_for :users
  # get 'dashboards/show'
  
  resources :coordinates
  resources :clients
  resources :quotes
  resources :tickets

  resources :invoices do
    collection do
      get 'cloudinary_invoices'
    end

    member do
      post 'save_to_cloudinary'
      get 'download_pdf'
      # delete 'destroy'
    end
  end
  
  get "invoices/:id/send", to: "invoices#send_mail", as: "send_mail"
  get 'print_quote/:id', to: 'quotes#show_another', as: 'print_quote'
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :user
    belongs_to :client
    validates :invoice_tva, presence: true
    validates :amount, presence: true
    validates :date, presence: true
    has_one_attached :cloudinary_file
    # validates :discount, default: 0
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_invoice, only: %i[show edit update destroy show_another save_to_cloudinary send_mail]
  
  def download_pdf
    pdf = InvoicePdf.new(@invoice, current_user)
    send_data pdf.render, filename: "facture-#{@invoice.invoice_number}.pdf", type: 'application/pdf', disposition: 'inline'
  end

  def save_to_cloudinary
    pdf = InvoicePdf.new(@invoice, current_user)
    pdf_data = pdf.render

    tempfile = Tempfile.new([@invoice.id.to_s, ".pdf"], binmode: true)
    tempfile.write(pdf_data)
    tempfile.rewind

    @invoice.cloudinary_file.attach(io: tempfile, filename: "invoice-#{@invoice.id}.pdf", content_type: 'application/pdf')
    tempfile.close
    tempfile.unlink

    flash[:notice] = "La facture a été sauvegardée sur Cloudinary avec succès."
    redirect_to cloudinary_invoices_invoices_path
  end

  def cloudinary_invoices
    @invoices = current_user.invoices.joins(:cloudinary_file_attachment).distinct
  end   
  
  def index
    @invoices = policy_scope(Invoice)
  end

  def show
    authorize @invoice
  end

  def show_another
  end

  def new
    @invoice = Invoice.new
    @user = current_user
    @clients = Client.where(user_id: @user.id)
  end

  def edit
    authorize @invoice
    @user = current_user
    @clients = Client.where(user_id: @user.id)
  end

  def update
    authorize @invoice
    if @invoice.update(invoice_params)
      redirect_to invoice_path(@invoice)
    else
      render :edit
    end
  end

  def send_mail
    @invoice = Invoice.find(params[:id])
    pdf = InvoicePdf.new(@invoice, current_user).render
  
    InvoiceMailer.send_invoice(@invoice, pdf).deliver_now
    @invoice.update(status: true)
    redirect_to invoices_path, notice: "Facture envoyée à #{@invoice.client.first_name}"
  end  

  def create
    @clients = Client.all
    @user = current_user
    @invoice = Invoice.new(invoice_params)
    authorize @invoice
    @invoice.user = @user
    if @invoice.save!
      redirect_to invoice_path(@invoice)
    else
      render :new
    end
  end

  def destroy
    authorize @invoice
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_path, notice: "Facture supprimée" }
      format.json { head :no_content }
    end
  end

  private
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def invoice_params
      params.require(:invoice).permit(:amount, :my_company_siret, :date, :description, :invoice_number, :prestation, :invoice_tva, :client_id, :discount)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<div class="container p-5" style="background-color: #fff; border: 1px solid #F4F4F4;">
  <%= simple_form_for(@invoice) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <div class="d-flex justify-content-center">
          <%= f.input :invoice_number, :label => "Numéro de facturation" %>
      </div>
      <div class="facture-informations">
        <div class="my-infos">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, width: 80, height: 80, :gravity=>"faces", :crop=>"fill", class: "rounded mb-5" %>
          <% end %>
          <h4>Facture éditée par :</h4>
          <%= current_user.first_name %> <%= current_user.last_name %><br>
          <%= current_user.address %><br>
          <%= current_user.phone %><br>
          <%= current_user.email %><br>
          <% if current_user.tva != nil %>
            N° TVA : <%= current_user.tva %><br>
          <% end %>
          Siret : <%= current_user.siret %>
        </div>
        <div class="informations-client">
          <div class="d-flex align-items-end flex-column">
               <%= f.input :client_id, collection: @clients, label_method: :first_name %>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-center w-100">
          <%= f.input :date, :label => "Date de facturation", as: :string, input_html: { data: { controller: 'flatpickr' } } %>
      </div>
          <%= f.input :description, :label => "Titre de la facture" %>
          <%= f.input :prestation, :label => "Prestations à facturer :" %>
      <div class="d-flex align-items-end flex-column w-20">
          <%= f.input :invoice_tva, value: "0%", collection: ["0%", "20%", "10%", "5.5%"], :label => "Taux de tva" %>
          <%= f.input :discount, :label => "Promotion : %" %>
          <%= f.input :amount, :label => "Total HT" %>
      </div>
          <h4>Informations de paiements :</h4><br>
          IBAN : <%= current_user.infos_payment %><br><br>
           <h4>Conditions de paiements :</h4><br>
           <%= current_user.conditions %><br><br>
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-success", value: "Créer ma facture" %>
    </div>
  <% end %>
</div>

app/views/invoices/_invoice.html.erb
<style>
.card-header{
  background-color: transparent;

}
#taille{
  height: 100px!important;
}
.card {
    border-radius: 10px;
    height: auto!important;
}
/* button.btn.btn-danger {
    padding: 3px;
}
a.btn.btn-primary {
    padding: 3px;
}
a.btn.btn-success {
    padding: 3px;
} */
</style>


<div class="container p-5">
<div class="d-flex flex-wrap">
    <% @invoices.reverse_each do |invoice| %>
      <div class="cardingspace">
        <% if invoice.user_id == current_user.id %>
          <div class="card text-center m-1">
            <div class="card-header">
              Facture N°:  <%= invoice.invoice_number %>
            </div>
            <div class="card-body">
              <h4 class="card-title">Facture à : <%= invoice.client.first_name %></h4>
              <p class="card-text"><%= invoice.description %><br></p>
              <b> Total :</b>
                <% total_tva = (invoice.amount * invoice.invoice_tva.to_f) / 100 %>
                <%= total_tva + invoice.amount %>€ TTC</p>
              <div class="d-flex justify-content-between spacing-mob">
                <a href="/invoices/<%= invoice.id %>" class="btn btn-primary"> Aperçu </a>
                <%= button_to "Supprimer", invoice, method: :delete, class: "btn btn-danger" %>
                <% if invoice.status == false %>
                <%= link_to "Envoyer", send_mail_path(invoice), class: "btn btn-success" %>
                <% end %>
              </div>
            </div>
            <% if invoice.status == true %>
                <p class="mt-3" style="color: green;"><b>Facture envoyée</b></p>
            <% else %>
                <p class="mt-3" style="color: red;"><b>Facture non envoyée</b></p>
            <% end %>
            <div class="card-footer text-muted">
              Facture créée le : <%= invoice.created_at %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/invoices/cloudinary_invoices.html.erb
<!-- app/views/invoices/cloudinary_invoices.html.erb -->
<div class="container" data-controller="pdf-modal">
  <h1>Mes factures sur Cloudinary</h1>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Numéro de facture</th>
          <th>Date</th>
          <th>Client</th>
          <th>Télécharger</th>
          <th>Supprimer</th>
        </tr>
      </thead>
      <tbody>
        <% @invoices.reverse_each do |invoice| %>
          <tr>
            <td><%= invoice.invoice_number %></td>
            <td><%= invoice.date %></td>
            <td><%= invoice.client.denomination %></td>
            <td>
              <%= link_to "Télécharger", url_for(invoice.cloudinary_file), target: "_blank", class: "btn btn-success" %>
            </td>
            <td>
              <%= button_to "Supprimer", invoice_path(invoice), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cette facture ?" }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <!-- Add data-pdf-modal-target="modal" to the modal div -->
  <div class="modal fade" id="pdfModal" tabindex="-1" aria-labelledby="pdfModalLabel" aria-hidden="true" data-pdf-modal-target="modal">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="pdfModalLabel">Facture</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <iframe data-pdf-modal-target="iframe" class="w-100 h-100" style="min-height: 80vh;"></iframe>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/invoices/edit.html.erb
<style>
.footer.mt-5 {
    display: none;
}
</style>
<div class="container">
  <h1>Modifier ma facture</h1>
</div>

<div class="container p-5" style="background-color: #fff; border: 1px solid #F4F4F4;">
  <%= simple_form_for(@invoice, url: invoice_path(@invoice), method: :patch) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <div class="d-flex justify-content-center">
          <%= f.input :invoice_number, :label => "Numéro de facturation" %>
      </div>
      <div class="facture-informations">
        <div class="my-infos">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, width: 80, height: 80, :gravity=>"faces", :crop=>"fill", class: "rounded mb-5" %>
          <% end %>
          <h4>Facture éditée par :</h4>
          <%= current_user.first_name %> <%= current_user.last_name %><br>
          <%= current_user.address %><br>
          <%= current_user.phone %><br>
          <%= current_user.email %><br>
          <% if current_user.tva != nil %>
            N° TVA : <%= current_user.tva %><br>
          <% end %>
          Siret : <%= current_user.siret %>
        </div>
        <div class="informations-client">
          <div class="d-flex align-items-end flex-column">
               <%= f.input :client_id, collection: @clients, label_method: :first_name %>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-center w-100">
          <%= f.input :date, :label => "Date de facturation", as: :string, input_html: { data: { controller: 'flatpickr' } } %>
      </div>
          <%= f.input :description, :label => "Titre de la facture" %>
          <%= f.input :prestation, :label => "Prestations à facturer :" %>
      <div class="d-flex align-items-end flex-column w-20">
          <%= f.input :invoice_tva, value: "0%", collection: ["0%", "20%", "10%", "5.5%"], :label => "Taux de tva" %>
          <%= f.input :discount, :label => "Promotion : %" %>
          <%= f.input :amount, :label => "Total HT" %>
      </div>
          <h4>Informations de paiements :</h4><br>
          IBAN : <%= current_user.infos_payment %><br><br>
           <h4>Conditions de paiements :</h4><br>
           <%= current_user.conditions %><br><br>
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-success", value: 'Modifier' %>
    </div>
  <% end %>
</div>

<br>

<div>
  <%= link_to "Voir ma facture", @invoice %> |
  <%= link_to "Retour à mes factures", invoices_path %>
</div>

app/views/invoices/index.html.erb
<style>
.footer.mt-5 {
    display: none;
}
</style>

<div class="container" data-controller="toggle">  
  <p style="color: green"><%= notice %></p>

  <h1>Vos factures</h1>
  <div class="d-flex justify-content-center">
    <button data-action="click->toggle#toggle" class="btn btn-primary m-2">
      <i class="bi bi-list"></i> Menu
    </button>
  </div>

  <div id="sidebar" class="sidebar" data-toggle-target="menu">
    <button data-action="click->toggle#disable" class="btn btn-close m-2">
      <i class="bi bi-x"></i>
    </button>
    <div class="d-flex flex-column align-items-start">
      <%#= link_to "Tableau de bord", dashboards_show_path, class: "btn btn-danger m-2" %>
      <%= link_to "Factures enregistrées", cloudinary_invoices_invoices_path, class: "btn btn-dark m-2" %>
      <%= link_to "Nouvelle facture", new_invoice_path, class:"btn btn-success m-2 text-white" %>
      <%= link_to "Mes clients", clients_path, class:"btn btn-info m-2 text-white" %>
      <%= link_to "Mes devis", quotes_path, class:"btn btn-primary m-2 text-white" %>
    </div>
  </div>

  <%# <div id="overlay" class="overlay" data-action="click->toggle#toggle"></div> %>

  <% if current_user.infos_payment == nil || current_user.conditions == nil %>
    <br><br>
    <p style="color: red;"> Vous n'avez pas configuré votre compte de facturation. <%= link_to "Cliquez ici", edit_user_registration_path %> pour le faire.</p>
  <% end %>

  <div id="invoices">
    <%= render "invoice" %>
  </div>
</div>

app/views/invoices/new.html.erb
<style>
.footer.mt-5 {
    display: none;
}
</style>
<div class="container d-flex justify-content-between">
  <h1>Créer ma facture</h1>
  <%= link_to "Ajouter un client", new_client_path, class: "btn btn-primary m-3" %>
</div>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Retour à mes factures", invoices_path %>
</div>

app/views/invoices/send_to_client.html.erb
<div style="padding: 50px;">
  <div>
    <h1 style= "font-family: sans-serif; margin:0 0 4px;font-size:21px;line-height:23px;font-weight:400;color:#333">Bonjour <%= @invoice.client.first_name %> <%= @invoice.client.last_name %>
    </h1>
  </div>
  <br>
  <p style="margin:0;font-size:15px;line-height:21px;color:#54595f;font-family: sans-serif;">Vous trouverez ci-joint la facture <strong style="font-weight:bold"><%= @invoice.description %></strong> du <strong style="font-weight:bold"><%=l(@invoice.created_at,format:"%A %d %B %Y") %></strong> d'un montant de <strong style="font-weight:bold"><%= @invoice.amount %> € HT</strong> pour la prestation <strong style="font-weight:bold"><%= @invoice.description %></strong>.</p>
  <br>
  <p style="margin:0;font-size:15px;line-height:21px;color:#54595f;font-family: sans-serif;">Je vous souhaite bonne réception,</p>
  <p style="margin:0;font-size:15px;line-height:21px;color:#54595f;font-family: sans-serif;">Dans l'attente du règlement de celle-ci, je reste à votre disposition.</p>
  <br>
  <br>
  <p style="margin:0;font-size:15px;line-height:21px;color:#54595f;font-family: sans-serif;">Cordialement,</p>
  <br>
  <br>
  <div class="d-flex justify-content-between" style="display:inline-flex;padding-bottom:10px;margin-top:8px; width:480px">
    <% if @invoice.user.photo.attached?  %>
      <div class="user-mail-pic" style="margin-right: 20px; max-width:35%">
        <%= cl_image_tag @invoice.user.photo.key, height: 65, width: 65, crop: :fill, style:"border-radius: 50%; vertical-align:initial; max-width:120px;" %>
      </div>
    <% end %>
    <div class="d-flex flex-column justify-content-between" style="width:65%; max-width:65%">
      <span style="font-size:12px;color:#263859;font-family:sans-serif;padding:0px;margin:0px;font-weight:bold;"><%= @invoice.user.first_name %> <%= @invoice.user.last_name %></span>
      <br>
      <p style="border-top:1px solid #01395f;line-height:0px; margin-top: 5px;margin-bottom: 5px; width: 70%;opacity: 0.8;"></p>
      <span style="font-size:12px; font-family: sans-serif;color: #263859; font-weight: bold; opacity: 0.8;"><%= @invoice.user.email %></span>
      <br>
      <span style="font-size:12px; font-family: sans-serif;color: #263859; font-weight: bold; opacity: 0.8;">SIRET : <%= @invoice.user.siret %></span>
      <br>
      <span style="font-size:12px; font-family: sans-serif;color: #263859; font-weight: bold; opacity: 0.8;"><%= @invoice.user.address %></span>
      <br>
      <span style="font-size:12px; font-family: sans-serif;color: #263859; font-weight: bold; opacity: 0.8;"><%= @invoice.user.phone %>
      </span>
    </div>
  </div>
</div>

app/views/invoices/send_to_client.js.erb
$('#invoice-div-<%= @invoice.id %>').html("<%= escape_javascript(render partial: 'invoices/invoices_index_partial/invoice_uniq', locals: { invoice: @invoice})%>");

app/views/invoices/send_to_client.text.erb
Bonjour <%= @invoice.client.first_name %> <%= @invoice.client.last_name %>

Vous trouverez ci-joint la facture <%= @invoice.invoice_number %> du  <%= @invoice.created_at %> d'un montant de <%= @invoice.amount  %> € HT pour la prestation <%= @invoice.description  %>.

Je vous souhaite bonne réception,
Dans l'attente du règlement de celle-ci, je reste à votre disposition.

Cordialement,
<%= @invoice.user.first_name %> <%= @invoice.user.last_name %>
Courriel : <%= @invoice.user.email %>
SIRET : <%= @invoice.user.siret %>
Adresse : <%= @invoice.user.address %>
Numéro : <%= @invoice.user.phone %>

app/views/invoices/show.html.erb
<style>
.footer.mt-5 {
    display: none;
}
/* button.btn.btn-danger {
    padding: 3px;
}
a.btn.btn-primary {
    padding: 3px;
}
a.btn.btn-success {
    padding: 3px;
} */
@media (max-width: 800px) {
button.btn.btn-danger {
    padding: 6px;
}
a.btn.btn-primary {
    padding: 6px;
}
a.btn.btn-success {
    padding: 6px;
}
}
</style>

<div data-controller="toggle" class="container">
  <div class="d-flex justify-content-center">
    <button data-action="click->toggle#toggle" class="btn btn-primary m-2">
      <i class="bi bi-list"></i> Menu
    </button>
  </div>

  <div id="sidebar" class="sidebar" data-toggle-target="menu">
    <button data-action="click->toggle#disable" class="btn btn-close m-2">
      <i class="bi bi-x"></i>
    </button>
    <div class="d-flex flex-column align-items-start">
      <%#= link_to "Mon tableau de bord", dashboards_show_path, class: "btn btn-danger m-2" %>
      <%= link_to "Mes factures", invoices_path, class: "btn btn-dark m-2" %>
      <%= form_with url: save_to_cloudinary_invoice_path(@invoice), method: :post do %>
        <%= submit_tag 'Sauvegarder', class: "btn btn-warning text-white m-2" %>
      <% end %>
      <%= link_to "Envoyer", send_mail_path(@invoice), class: "btn btn-success m-2" %>
      <%= link_to "Modifier", edit_invoice_path(@invoice), class: "btn btn-primary m-2" %>
      <%= button_to "Supprimer", @invoice, method: :delete, class: "btn btn-danger m-2" %>
    </div>
  </div>
  <p style="color: green"><%= notice %></p>

	<div class="invoice-box">
				<table cellpadding="0" cellspacing="0">
					<tr class="top">
						<td colspan="2">
							<table>
								<tr>
									<td class="title">
										<% if current_user.photo.attached? %>
						<%= cl_image_tag current_user.photo.key, :gravity=>"faces", :crop=>"fill", width: 80, height: 80, class: "rounded mb-5" %>
						<% end %>
									</td>

									<td>
										Facture n° #: <%= @invoice.invoice_number %><br />
										Créée: <%= @invoice.date %><br />
									</td>
								</tr>
							</table>
						</td>
					</tr>

					<tr class="information">
						<td colspan="2">
							<table>
								<tr>
									<td>
										<%= current_user.first_name %> <%= current_user.last_name %><br />
										<%= current_user.address %><br />
					<%= current_user.phone %><br />
					<%= current_user.email %><br />
										N° Siret : <%= current_user.siret %><br />
					<%= current_user.tva if current_user.tva != nil %><br />
					<p class="mt-3 text-center"><b>Titre de la facture : <%= @invoice.description.camelcase %></b></p>
									</td>

									<td>
										<%= @invoice.client.first_name %> <%= @invoice.client.denomination %><br />
										<%= @invoice.client.email %><br />
										<%= @invoice.client.compagny_address %>
					<%= @invoice.client.compagny_siret if @invoice.client.compagny_siret != nil %>
									</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr class="heading">
						<td>Informations de paiements :</td>

						<td></td>
					</tr>

					<tr class="details">
						<td><%= current_user.infos_payment %></td>

						<td></td>
					</tr>

					<tr class="heading">
						<td>Description</td>

						<td>Prix HT</td>
					</tr>

					<tr class="item">
						<td><%= @invoice.prestation %></td>

						<td><%= @invoice.amount %>€ HT</td>
					</tr>

					<% if @invoice.discount == nil %>
						<% @invoice.discount = 0 %>
					<% end %>
					<tr class="total">
					<td> Promotion : <b><%= @invoice.discount %>%</b></td>
					<% total_tva = (@invoice.amount * @invoice.invoice_tva.to_f) / 100 %>
						<td> Total TVA : <%= total_tva %>€<br>
						<% with_tva = (total_tva + @invoice.amount.to_f) %>
						<% first_step = (with_tva.to_i * @invoice.discount) / 100 %>
						<% second_step = with_tva - first_step %>
						Total : <%= second_step %>€ TTC </td>
					</tr>
			<td style="margin-top: 20px!important;"><%= current_user.conditions %></td>
				</table>
	</div>
</div>

app/views/invoices/show_another.html.erb
<style>
.footer.mt-5 {
    display: none;
}
.navbar.navbar-expand-sm.navbar-light.navbar-lewagon.fixed-top {
    display: none;
}
body {
    margin-top: 10px;
}
.container {
    min-width: 1000px;
}
</style>
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="invoice-box">
			<table cellpadding="0" cellspacing="0">
				<tr class="top">
					<td colspan="2">
						<table>
							<tr>
								<td class="title">
									  <% if current_user.photo.attached? %>
                      <%= cl_image_tag current_user.photo.key, :gravity=>"faces", :crop=>"fill", width: 80, height: 80, class: "rounded mb-5" %>
                    <% end %>
								</td>

								<td>
									Facture n° #: <%= @invoice.invoice_number %><br />
									Créée: <%= @invoice.date %><br />
								</td>
							</tr>
						</table>
					</td>
				</tr>

				<tr class="information">
					<td colspan="2">
						<table>
							<tr>
								<td>
									<%= current_user.first_name %> <%= current_user.last_name %><br />
									<%= current_user.address %><br />
                  <%= current_user.phone %><br />
                  <%= current_user.email %><br />
									N° Siret : <%= current_user.siret %><br />
                  <%= current_user.tva if current_user.tva != nil %><br />
                  <p class="mt-3 text-center"><b>Titre de la facture : <%= @invoice.description.camelcase %></b></p>
								</td>

								<td>
									<%= @invoice.client.first_name %> <%= @invoice.client.denomination %><br />
									<%= @invoice.client.email %><br />
									<%= @invoice.client.compagny_address %>
                  <%= @invoice.client.compagny_siret if @invoice.client.compagny_siret != nil %>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr class="heading">
					<td>Informations de paiements :</td>

					<td></td>
				</tr>

				<tr class="details">
					<td><%= current_user.infos_payment %></td>

					<td></td>
				</tr>

				<tr class="heading">
					<td>Description</td>

					<td>Prix HT</td>
				</tr>

				<tr class="item">
					<td><%= @invoice.prestation %></td>

					<td><%= @invoice.amount %>€ HT</td>
				</tr>

				<tr class="total">
					<td> Promotion : <b><%= @invoice.discount %>%</b></td>
					<% total_tva = (@invoice.amount * @invoice.invoice_tva.to_f) / 100 %>
						<td> Total TVA : <%= total_tva %>€<br>
						<% with_tva = (total_tva + @invoice.amount) %>
						<% first_step = (with_tva.to_i * @invoice.discount) / 100 %>
						<% second_step = with_tva - first_step %>
						Total : <%= second_step %>€ TTC </td>
					</tr>
          <td style="margin-top: 20px!important;"><%= current_user.conditions %></td>
			</table>
		</div>
</div>