config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  mount RailsAdmin::Engine => '/exit', as: 'rails_admin'
  
  devise_for :users
  # get 'dashboards/show'
  
  resources :coordinates
  resources :clients
  resources :quotes
  resources :tickets

  resources :invoices do
    collection do
      get 'cloudinary_invoices'
    end

    member do
      post 'save_to_cloudinary'
      get 'download_pdf'
      # delete 'destroy'
    end
  end
  
  get "invoices/:id/send", to: "invoices#send_mail", as: "send_mail"
  get 'print_quote/:id', to: 'quotes#show_another', as: 'print_quote'
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :user
    belongs_to :client
    validates :invoice_tva, presence: true
    validates :amount, presence: true
    validates :date, presence: true
    has_one_attached :cloudinary_file
    # validates :discount, default: 0
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_invoice, only: %i[show edit update destroy show_another save_to_cloudinary send_mail]
  
  def download_pdf
    pdf = InvoicePdf.new(@invoice, current_user)
    send_data pdf.render, filename: "facture-#{@invoice.invoice_number}.pdf", type: 'application/pdf', disposition: 'inline'
  end

  def save_to_cloudinary
    pdf = InvoicePdf.new(@invoice, current_user)
    pdf_data = pdf.render

    tempfile = Tempfile.new([@invoice.id.to_s, ".pdf"], binmode: true)
    tempfile.write(pdf_data)
    tempfile.rewind

    @invoice.cloudinary_file.attach(io: tempfile, filename: "invoice-#{@invoice.id}.pdf", content_type: 'application/pdf')
    tempfile.close
    tempfile.unlink

    flash[:notice] = "La facture a été sauvegardée sur Cloudinary avec succès."
    redirect_to cloudinary_invoices_invoices_path
  end

  def cloudinary_invoices
    @invoices = current_user.invoices.joins(:cloudinary_file_attachment).distinct
  end   
  
  def index
    @invoices = policy_scope(Invoice)
  end

  def show
    authorize @invoice
  end

  def show_another
  end

  def new
    @invoice = Invoice.new
    @user = current_user
    @clients = Client.where(user_id: @user.id)
  end

  def edit
    authorize @invoice
    @user = current_user
    @clients = Client.where(user_id: @user.id)
  end

  def update
    authorize @invoice
    if @invoice.update(invoice_params)
      redirect_to invoice_path(@invoice)
    else
      render :edit
    end
  end

  def send_mail
    @invoice = Invoice.find(params[:id])
    pdf = InvoicePdf.new(@invoice, current_user).render
  
    InvoiceMailer.send_invoice(@invoice, pdf).deliver_now
    @invoice.update(status: true)
    redirect_to invoices_path, notice: "Facture envoyée à #{@invoice.client.first_name}"
  end  

  def create
    @clients = Client.all
    @user = current_user
    @invoice = Invoice.new(invoice_params)
    authorize @invoice
    @invoice.user = @user
    if @invoice.save!
      redirect_to invoice_path(@invoice)
    else
      render :new
    end
  end

  def destroy
    authorize @invoice
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_path, notice: "Facture supprimée" }
      format.json { head :no_content }
    end
  end

  private
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def invoice_params
      params.require(:invoice).permit(:amount, :my_company_siret, :date, :description, :invoice_number, :prestation, :invoice_tva, :client_id, :discount)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/pdf/show.pdf.erb
<style>
.footer.mt-5 {
    display: none;
}
button.btn.btn-danger {
    padding: 3px;
}
a.btn.btn-primary {
    padding: 3px;
}
a.btn.btn-success {
    padding: 3px;
}
@media (max-width: 800px) {
button.btn.btn-danger {
    padding: 6px;
}
a.btn.btn-primary {
    padding: 6px;
}
a.btn.btn-success {
    padding: 6px;
}
}
</style>
<div class="container">
 <form class="d-flex justify-content-center">
    <%= link_to "Mes factures", invoices_path, class: "btn btn-dark m-2 btn-mob" %>
    <%= link_to "Enregistrer", print_path(@invoice), target: "_blank", class: "btn btn-warning text-white m-2" %>
    <%= link_to "Envoyer", send_mail_path(@invoice), class: "btn btn-success m-2" %>
    <%= link_to "Modifier", edit_invoice_path(@invoice), class: "btn btn-primary m-2" %>
	<%= button_to "Supprimer", @invoice, method: :delete, class: "btn btn-danger m-2" %>
  </form>
  <p style="color: green"><%= notice %></p>
<p>Invoice ID: <%= invoice.id %></p>
<p>Client: <%= invoice.client.name %></p>
	<div class="invoice-box">
				<table cellpadding="0" cellspacing="0">
					<tr class="top">
						<td colspan="2">
							<table>
								<tr>
									<td class="title">
										<% if current_user.photo.attached? %>
						<%= cl_image_tag current_user.photo.key, :gravity=>"faces", :crop=>"fill", width: 80, height: 80, class: "rounded mb-5" %>
						<% end %>
									</td>

									<td>
										Facture n° #: <%= @invoice.invoice_number %><br />
										Créée: <%= @invoice.date %><br />
									</td>
								</tr>
							</table>
						</td>
					</tr>

					<tr class="information">
						<td colspan="2">
							<table>
								<tr>
									<td>
										<%= current_user.first_name %> <%= current_user.last_name %><br />
										<%= current_user.address %><br />
					<%= current_user.phone %><br />
					<%= current_user.email %><br />
										N° Siret : <%= current_user.siret %><br />
					<%= current_user.tva if current_user.tva != nil %><br />
					<p class="mt-3 text-center"><b>Titre de la facture : <%= @invoice.description.camelcase %></b></p>
									</td>

									<td>
										<%= @invoice.client.first_name %> <%= @invoice.client.denomination %><br />
										<%= @invoice.client.email %><br />
										<%= @invoice.client.compagny_address %>
					<%= @invoice.client.compagny_siret if @invoice.client.compagny_siret != nil %>
									</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr class="heading">
						<td>Informations de paiements :</td>

						<td></td>
					</tr>

					<tr class="details">
						<td><%= current_user.infos_payment %></td>

						<td></td>
					</tr>

					<tr class="heading">
						<td>Description</td>

						<td>Prix HT</td>
					</tr>

					<tr class="item">
						<td><%= @invoice.prestation %></td>

						<td><%= @invoice.amount %>€ HT</td>
					</tr>

					<% if @invoice.discount == nil %>
						<% @invoice.discount = 0 %>
					<% end %>
					<tr class="total">
					<td> Promotion : <b><%= @invoice.discount %>%</b></td>
					<% total_tva = (@invoice.amount * @invoice.invoice_tva.to_f) / 100 %>
						<td> Total TVA : <%= total_tva %>€<br>
						<% with_tva = (total_tva + @invoice.amount) %>
						<% first_step = (with_tva.to_i * @invoice.discount) / 100 %>
						<% second_step = with_tva - first_step %>
						Total : <%= second_step %>€ TTC </td>
					</tr>
			<td style="margin-top: 20px!important;"><%= current_user.conditions %></td>
				</table>
	</div>
</div>