config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  mount RailsAdmin::Engine => '/exit', as: 'rails_admin'
  
  devise_for :users
  # get 'dashboards/show'
  
  resources :coordinates
  resources :clients
  resources :quotes
  resources :tickets

  resources :invoices do
    collection do
      get 'cloudinary_invoices'
    end

    member do
      post 'save_to_cloudinary'
      get 'download_pdf'
      # delete 'destroy'
    end
  end
  
  get "invoices/:id/send", to: "invoices#send_mail", as: "send_mail"
  get 'print_quote/:id', to: 'quotes#show_another', as: 'print_quote'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    belongs_to :user
    has_many :quotes, dependent: :destroy
end

app/models/cloud.rb
class Cloud < ApplicationRecord
    has_many_attached :photos
    belongs_to :user, dependent: :destroy
end

app/models/export.rb
class Export < ApplicationRecord
    belongs_to :invoice
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :user
    belongs_to :client
    validates :invoice_tva, presence: true
    validates :amount, presence: true
    validates :date, presence: true
    has_one_attached :cloudinary_file
    # validates :discount, default: 0
end

app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :user
    belongs_to :client

    validates :quote_tva, presence: { message: "Le champ TVA doit être rempli" }
    validates :amount, presence: { message: "Le champ Montant doit être rempli" }
    validates :date, presence: { message: "Le champ Date doit être rempli" }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    # belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :invoices, dependent: :destroy
  has_many :clients, dependent: :destroy
  has_many :quotes, dependent: :destroy
  # has_many :tickets, dependent: :destroy
  has_one_attached :photo
end

app/controllers/clouds_controller.rb
class CloudsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: [:index, :new, :create, :show, :destroy]
    def index
        @cloud = Cloud.where(user: current_user)
    end
    def new
        @cloud = Cloud.new
    end
    def create
        @cloud = Cloud.new(cloud_params)
        @cloud.user = @user
        if @cloud.save
            redirect_to cloud_path(@cloud)
        else
            render :new
        end
    end
    def destroy
        @cloud.destroy
        redirect_to user_path(@user)
    end

    private
    def cloud_params
        params.require(:cloud).permit(photos: [])
    end
    def set_user
        @user = current_user
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def password
    end
    
    def actu
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_quote, only: %i[show edit update destroy show_another]
  
    def index
      @quotes = policy_scope(Quote)
    end
  
    def show
      authorize @quote
    end
  
    def show_another
    end
  
    def new
      @quote = Quote.new
      @clients = Client.where(user_id: current_user.id)
    end
  
    def edit
      @clients = Client.where(user_id: current_user.id)
    end
  
    def create
      @quote = Quote.new(quote_params)
      @quote.user = current_user
      if @quote.save!
        redirect_to quote_url(@quote), notice: "Devis créé"
      else
        flash.now[:alert] = "La création du devis a échoué."
        puts @quote.errors.full_messages # Afficher les messages d'erreur dans la console
        render :new, status: :unprocessable_entity
      end
    end
  
    def update
      authorize @quote
  
      if @quote.update(quote_params)
        redirect_to quote_url(@quote), notice: "Devis mis à jour"
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      authorize @quote
      @quote.destroy
  
      redirect_to quotes_url, notice: "Devis supprimé"
    end
  
    private
  
    def set_quote
      @quote = Quote.find(params[:id])
    end
  
    def quote_params
      params.require(:quote).permit(:amount, :my_company_siret, :date, :description, :quote_number, :prestation, :quote_tva, :client_id)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/clouds_helper.rb
module CloudsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/exports_helper.rb
module ExportsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_google.html.erb
<meta name="google-site-verification" content="i89kFey0Aw94cfPYBEyn3icGq-01dOEwYIarFQynOPg" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>As WEB</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="icon" href="https://as-web.website/wp-content/uploads/2022/02/Group-1-1.png" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
  <%= render 'layouts/google' %>
</head>
<body data-turbo-suppress-warning="">
  <%= render '/shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= render "shared/footer" %>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" defer crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" defer crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Invoice PDF</title>
  <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
  <%= wicked_pdf_javascript_include_tag 'pdf' %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<meta name="description" content="Outils pour les développeurs - AS-Web application">
<%= render "/shared/banner" %>
<div class="container mt-5">
    <%= render "/shared/cardsbootstrap" %>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="object-fit: cover; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.pinimg.com/originals/81/17/8b/81178b47a8598f0c81c4799f2cdd4057.gif);">
  <div class="container">
    <h1 class="typed" data-controller="typed-js"></h1>
    <p class="text-white">Découvrez notre plateforme tout-en-un pour gérer vos invoices, devis et bien plus encore. Accédez à notre sélection d'outils internes et externes pour optimiser votre travail au quotidien.</p>
    <a class="btn btn-flat" href="/#outils">Voir tous les outils</a>
    <a class="btn btn-danger" href="/invoices">Outil de facturation</a>
  </div>
</div>

app/views/shared/_cardsbootstrap.html.erb
<div class="row row-cols-2 row-cols-md-3 g-4">
<div class="col">
    <div class="card m-3">
      <img src="https://kinsta.com/fr/wp-content/uploads/sites/4/2019/02/que-sont-dns.png" class="card-img-top" alt="heroku nom de domaine">
      <div class="card-body">
        <h5 class="card-title"><%= link_to "Vérifier votre configuration DNS", 'https://dns.as-web.website/' %></h5>
        <p class="card-text">Vérifier les DNS d'un nom de domaine en tant réel. Surveillez votre propagation DNS. Vérifiez que vous avez bien connecter votre nom de domaine à <b>Heroku</b></p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card m-3">
      <img src="https://images.unsplash.com/photo-1649209979970-f01d950cc5ed?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3282&q=80" class="card-img-top" alt="créer une facture">
      <div class="card-body">
        <h5 class="card-title"> <%= link_to "Outil de facturation", invoices_path %></h5>
        <p class="card-text">Créer et sauvegarder vos factures sur votre espace ! Exporter en pdf vos factures pour les envoyer à vos clients. Configurer votre compte et le tour est joué !</p>
      </div>
    </div>
  </div>
  <!-- <div class="col">
    <div class="card m-3">
      <img src="https://images.unsplash.com/photo-1642013352168-ccb46a0ac67f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2342&q=80" class="card-img-top" alt="illustration emoji">
      <div class="card-body">
        <h5 class="card-title"><%= link_to "Récupérer les points gps d'une adresse", coordinates_path %></h5>
        <p class="card-text">Récupérer vos coordonnées gps à partir d'une adresse donnée. API gratuite, système de mapping pour vérifier votre adresse.</p>
      </div>
    </div>
  </div> -->
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-5">
  <div class="footer-links">
    <a href="https://github.com/alexisjps/"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    Fait avec <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="navbar-brand">
    <%= link_to root_path do %>
      <%= image_tag "https://as-web.website/wp-content/uploads/2022/02/Logo-AlexStephan-AS-web.png", alt: "logo AS WEB", width: "200px" %>
    <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
          <li class="nav-item active">
            <%= link_to "Accueil", "/", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Facturation
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%#= link_to "Dashboard", dashboards_show_path, class: "dropdown-item" %></li>
              <li><%= link_to "Toutes mes factures", "/invoices", class: "dropdown-item" %></li>
              <li><%= link_to "Factures enregistrées", "/invoices/cloudinary_invoices", class: "dropdown-item", data: { turbo: false } %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Nouvelle facture", new_invoice_path, class: "dropdown-item" %></li>
              <li><%= link_to "Nouveau devis", new_quote_path, class: "dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item active">
            <%= link_to "Blog", "https://as-web.website/blog", class: "nav-link", target: "_blank" %>
          </li>
          <% if current_user != nil %>
          <% if current_user.photo.attached? %>
            <span class="dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"><%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :fill, :gravity=> "face", class: "rounded" %></span>
            <% else %>
            <span class="dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"><img style="width: 40px; height: 40px; border-radius: 100px;" src="https://res.cloudinary.com/hello-my-business/image/upload/v1671101861/Screenshot_2022-12-15_at_11.56.59-removebg-preview_mfdlge.png"></span>
            <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "Modifier mon profil", edit_user_registration_path, class: "dropdown-item" %></li>
            <li><%= link_to "Déconnexion", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %></li>
          </ul>
          <% end %>
      </ul>
    </div>
  </div>
</div>